// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketSystem.Models;

namespace TicketSystem.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20210316040240_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TicketSystem.Models.Point", b =>
                {
                    b.Property<string>("PointId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PointId");

                    b.ToTable("Point");

                    b.HasData(
                        new
                        {
                            PointId = "a",
                            Name = "1"
                        },
                        new
                        {
                            PointId = "b",
                            Name = "2"
                        },
                        new
                        {
                            PointId = "c",
                            Name = "3"
                        },
                        new
                        {
                            PointId = "d",
                            Name = "4"
                        },
                        new
                        {
                            PointId = "e",
                            Name = "5"
                        },
                        new
                        {
                            PointId = "f",
                            Name = "6"
                        },
                        new
                        {
                            PointId = "g",
                            Name = "7"
                        },
                        new
                        {
                            PointId = "h",
                            Name = "8"
                        },
                        new
                        {
                            PointId = "i",
                            Name = "9"
                        },
                        new
                        {
                            PointId = "j",
                            Name = "10"
                        },
                        new
                        {
                            PointId = "k",
                            Name = "11"
                        },
                        new
                        {
                            PointId = "l",
                            Name = "12"
                        },
                        new
                        {
                            PointId = "m",
                            Name = "13"
                        },
                        new
                        {
                            PointId = "n",
                            Name = "14"
                        },
                        new
                        {
                            PointId = "o",
                            Name = "15"
                        },
                        new
                        {
                            PointId = "p",
                            Name = "16"
                        },
                        new
                        {
                            PointId = "q",
                            Name = "17"
                        },
                        new
                        {
                            PointId = "r",
                            Name = "18"
                        },
                        new
                        {
                            PointId = "s",
                            Name = "19"
                        },
                        new
                        {
                            PointId = "t",
                            Name = "20"
                        });
                });

            modelBuilder.Entity("TicketSystem.Models.SprintNum", b =>
                {
                    b.Property<string>("SprintNumId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SprintNumId");

                    b.ToTable("SprintNum");

                    b.HasData(
                        new
                        {
                            SprintNumId = "a",
                            Name = "0"
                        },
                        new
                        {
                            SprintNumId = "b",
                            Name = "1"
                        },
                        new
                        {
                            SprintNumId = "c",
                            Name = "2"
                        },
                        new
                        {
                            SprintNumId = "d",
                            Name = "3"
                        },
                        new
                        {
                            SprintNumId = "e",
                            Name = "4"
                        },
                        new
                        {
                            SprintNumId = "f",
                            Name = "5"
                        },
                        new
                        {
                            SprintNumId = "g",
                            Name = "6"
                        },
                        new
                        {
                            SprintNumId = "h",
                            Name = "7"
                        },
                        new
                        {
                            SprintNumId = "i",
                            Name = "8"
                        },
                        new
                        {
                            SprintNumId = "j",
                            Name = "9"
                        },
                        new
                        {
                            SprintNumId = "k",
                            Name = "10"
                        },
                        new
                        {
                            SprintNumId = "l",
                            Name = "11"
                        },
                        new
                        {
                            SprintNumId = "m",
                            Name = "12"
                        },
                        new
                        {
                            SprintNumId = "n",
                            Name = "13"
                        },
                        new
                        {
                            SprintNumId = "o",
                            Name = "14"
                        },
                        new
                        {
                            SprintNumId = "p",
                            Name = "15"
                        },
                        new
                        {
                            SprintNumId = "q",
                            Name = "16"
                        },
                        new
                        {
                            SprintNumId = "r",
                            Name = "17"
                        },
                        new
                        {
                            SprintNumId = "s",
                            Name = "18"
                        },
                        new
                        {
                            SprintNumId = "t",
                            Name = "19"
                        },
                        new
                        {
                            SprintNumId = "u",
                            Name = "20"
                        });
                });

            modelBuilder.Entity("TicketSystem.Models.Status", b =>
                {
                    b.Property<string>("StatusId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = "todo",
                            Name = "To Do"
                        },
                        new
                        {
                            StatusId = "wip",
                            Name = "In Progress"
                        },
                        new
                        {
                            StatusId = "qa",
                            Name = "Quality Assurance"
                        },
                        new
                        {
                            StatusId = "closed",
                            Name = "Done"
                        });
                });

            modelBuilder.Entity("TicketSystem.Models.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PointId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SprintNumId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PointId");

                    b.HasIndex("SprintNumId");

                    b.HasIndex("StatusId");

                    b.ToTable("ToDos");
                });

            modelBuilder.Entity("TicketSystem.Models.ToDo", b =>
                {
                    b.HasOne("TicketSystem.Models.Point", "Point")
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketSystem.Models.SprintNum", "SprintNum")
                        .WithMany()
                        .HasForeignKey("SprintNumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketSystem.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Point");

                    b.Navigation("SprintNum");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
